
services:
  sanJy_database:
    image: postgres:17-alpine
    container_name: sanJy_database
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      # ADM
      POSTGRES_USER: admin_usr
      POSTGRES_PASSWORD: admin_pass
      POSTGRES_DB: diet_control
    volumes:
      - sanJy_database:/var/lib/postgresql/data

volumes:
  sanJy_database:
