##################
# BUILD STEP
##################

FROM eclipse-temurin:25.0.1_8-jdk-alpine-3.22 AS build

WORKDIR /app

# Install necessary packages
RUN apk add --no-cache make

# Copy dependency files and resolve dependencies offline
COPY core core
COPY entrypoint entrypoint
COPY infrastructure infrastructure
COPY lombok.config .
COPY Makefile .
COPY pom.xml .
COPY mvnw .
COPY .mvn .mvn

# Build
RUN make build/jvm

##################
# RELEASE STEP
##################
FROM eclipse-temurin:25.0.1_8-jdk-alpine-3.22 AS release

WORKDIR /app

# Copy the built jar from the build stage
COPY --from=build /app/infrastructure/target/*.jar ./app.jar

# ToDo: Colocar healthcheck e observabilidade
# Copy healthcheck script
#COPY healthcheck.sh .

# Set up directories
ARG S_DATA_PATH=/app/data
RUN mkdir -p ${S_DATA_PATH}/logs/structured \
    && mkdir -p ${S_DATA_PATH}/logs/unstructured

# Create non-root user
RUN addgroup -g 1000 sanjy && \
    adduser -u 1000 -G sanjy -s /bin/sh -D sanjy && \
    chown -R sanjy:sanjy /app

# Switch to non-root user for running the app
USER sanjy

# Expose the application port
EXPOSE 8080

# Set the final entrypoint
ENTRYPOINT ["java", "-Dfile.encoding=UTF-8", "-Dlog4j2.formatMsgNoLookups=true", "-jar", "/app/app.jar"]