##################
# BUILD ARGUMENTS
##################

# Define BUILD_MODE at global scope to be used in FROM instructions
ARG BUILD_MODE=full

##################
# BUILD STEP (FULL MODE)
##################
FROM eclipse-temurin:25.0.1_8-jdk-alpine-3.22 AS build-full

RUN echo "========================================" && \
    echo "STAGE: build-full (JVM full compilation)" && \
    echo "========================================"

WORKDIR /app

# Install necessary packages
RUN apk add --no-cache make

# Copy dependency files and resolve dependencies offline
COPY core core
COPY entrypoint entrypoint
COPY infrastructure infrastructure
COPY aggregate-report aggregate-report
COPY lombok.config .
COPY Makefile .
COPY pom.xml .
COPY mvnw .
COPY .mvn .mvn

# Build and move JAR to standard location
RUN make build/jvm && \
    mv infrastructure/target/*.jar /app/app.jar

##################
# BUILD STEP (LOCAL MODE)
##################
FROM eclipse-temurin:25.0.1_8-jdk-alpine-3.22 AS build-local

RUN echo "========================================" && \
    echo "STAGE: build-local (using pre-built JAR)" && \
    echo "========================================"

WORKDIR /app

# Copy pre-built jar from local build
COPY infrastructure/target/*.jar ./app.jar

##################
# RELEASE STEP
##################
FROM build-${BUILD_MODE} AS build-selected

FROM eclipse-temurin:25.0.1_8-jdk-alpine-3.22 AS release

RUN echo "========================================" && \
    echo "STAGE: release (final image)" && \
    echo "========================================"

WORKDIR /app

# Copy the jar (either from build-full or build-local)
COPY --from=build-selected /app/*.jar ./app.jar

# ToDo: Colocar healthcheck e observabilidade
# Copy healthcheck script
#COPY healthcheck.sh .

# Set up directories
ARG S_DATA_PATH=/app/data
RUN mkdir -p ${S_DATA_PATH}/logs/structured \
    && mkdir -p ${S_DATA_PATH}/logs/unstructured

# Create non-root user
RUN addgroup -g 1000 sanjy && \
    adduser -u 1000 -G sanjy -s /bin/sh -D sanjy && \
    chown -R sanjy:sanjy /app

# Switch to non-root user for running the app
USER sanjy

# Expose the application port
EXPOSE 8080

# Set the final entrypoint
ENTRYPOINT ["java", "-Dfile.encoding=UTF-8", "-Dlog4j2.formatMsgNoLookups=true", "-jar", "/app/app.jar"]
